#!/usr/bin/lua
package.path = package.path .. ";../?.lua"

require 'getopt'
require 'lisp'

require 'vertaal'
require 'bouw'
require 'doe'

local opt,bronnen = getopt({...}, "u")

for i,bron in pairs(bronnen) do
	if bron:sub(-5) ~= '.code' then
		bronnen[i] = bron .. '.code'
	end
end

if #bronnen == 0 then
	print('geen invoer')
end

if opt.h or opt.help or #bronnen == 0 then
	print(
[[gebruik: vt [OPTIES...] [BESTANDEN...]
Vertaalt broncode naar applicaties.
Opties:
    -h, --help        print deze hulp
    -d, --doe         voer meteen uit
    -s, --syntax     	print syntax
    -l, --lokale=CC	  stel lokale van broncode in (standaard NL)
    -u, --uitvoer=UIT	uitvoerbestand
    -v, --verboos     spraakzaam zijn
]])
	return
end

if opt.v or opt.verboos then
	verboos = true
end

local code = file(bronnen[1])

local plan = vertaal(code, 'in', 'uit')
local uit
		
if opt.d or opt.doe then
	uit = doe(plan)
else
	uit = bouw(plan)
end
uit = unlisp(uit)

local u = opt.u or opt.uitvoer
if u then
	file(u, uit)
else
	print(unlisp(uit))
end
