sas: '\n'? exp ('\n' exp)*
block: INDENT ('\n' indent exp)+ DEDENT
exp: if | function | block
function: infix | side

blockfix: INDENT ('\n' indent blockop exp)+ DEDENT
infix: (side binop)+ (block | side | blockfix)
uatom: ubin | upre | atom1
ubin: atom1 atom1 atom1
upre: atom1 (atom1 | blockfix)

side: uatom | prefix
prefix: unop+ atom1

atom1: brackets | identifier | number | text | list | set

atom:
	| brackets | prefix | identifier | number | text
	| list | set
	| blockfix

list: '[' collection ']'
set: '{' collection '}'
params: '(' collection ')'

collection: INDENT exp? (sep exp)* DEDENT '\n'? indent?
sep: ('\n' indent) | ','

brackets: '(' (block|exp) '\n'? ')'
prefix1: unop atom
identifier: SAS-ID
number: NUMBER
text: STRING

unop: '#' | '_' | '^' | '!' | '-' | '+-'
blockop: '+' | '*' | '|' | '&' | '@'
binop:
	| '.'
	| '^' | '_'
	| '*' | '/' | '%'
	| '+' | '-' | '+-'
	| '..'
	| '||'
	| '>' | '<' | '>=' | '<=' | '=' | '!='
	| 'in' | 'as' | ':' | 'is'
	| '|' | '\\' | '&' | 'xor' | 'nor' | 'and' | 'or'
	| '>>' | '<<' | '@' | '->' 
	| '=>' | '<=>'

; IF
; inline if bestaat ff niet

newline: '\n'
if: ruleif | blockif
ruleif:
	'if' block newline
	'then' block
	(newline 'else' INDENT block DEDENT)?
; moet hier end bij?

blockif:
	'if' exp block
	(newline indent 'elseif' exp block)*
	(newline indent 'else' block)?

inlineif:
	'if' exp 'then' exp 'else' exp 'end'?
