sas: exp
eol: '\n'
comment: ';' (^newline)*
newline: comment? newline
number: decimal | hexadecimal | binary | quaternary
int: (plus | minus)? digit+
decimal: int (dot digit+)? ('e' int)?
indent: tab*INDENT-DEPTH
escaped: backslash (backslash | quote | 'n' | 't' | 'e' | Alphanum*2)
text: quote (escaped | (^quote))* quote
empty: space | tab | newline
reserved: 'if' | 'else' | 'elseif'
all-symbols: letter+ (dash (letter | digit)+)*  
symbol: all-symbols - reserved
whitespace: empty*
