#!/usr/bin/lua
package.path = package.path..';../?.lua'

require 'naarlua'
require 'infix'
require 'rapporteer-syntax'

require 'ontleed'
require 'typeer'
require 'oplos'

local socket = require 'socket'
local server = socket.bind('127.0.0.1','1237')
assert(server)
local sockets = {server}
local coros = {}

os.execute("chromium localhost:1237 &")

-- DE webfunctie
-- vt: code → exp?, fouten?
--   fouten: [ fout... ]
--   fout: syntaxfout | typefout | oplosfout
--     syntaxfout: { type="syntax", loc, bericht }
--     typefout: { type="typeer", ? }
--     oplosfout: { type="oplos", ? }
-- 
-- de "fout" als los interpretabel object
function vt(code)
	local exp,syntaxfouten = ontleed(code)
	local types,typeerfouten = typeer(exp)
	local waarde,oplosfouten

	if not typefouten then
		waarde,oplosfouten = oplos(exp)
	end

	-- foutje kan gebeuren
	local fouten
	if syntaxfouten or typefouten or oplosfouten then
		fouten = cat(syntaxfouten or {}, typefouten or {}, oplosfouten or {})
	end

	return waarde, fouten
end

local statusberichten = {
	[200] = "Okee",
	[302] = "Permanente Omleiding",
	[404] = "Niet Gevonden",
	[500] = "Interne Fout",
}

function sendblocking(sock, data)
	local i = 1
	while i < #data do
		local len,err = sock:send(data, i, #data)
		if not len then return nil,err end
		i = i + len + 1 -- laatst verzonden byte
	end
	return #data
end

function serveer(sock)
	local len

	-- header
  coroutine.yield()
	local line = sock:receive('*l')
	local methode,pad = line:match("([^ ]*) ([^ ]*) ([^ ]*)")

	while true do
		coroutine.yield()
		local line = sock:receive('*l')
		if line == '' then
			break
		end
		
		local len0 = line:match('Content%-Length: (%d+)')
		if len0 then
			len = tonumber(len0)
		end
	end

	-- content
	local inn
	local uit
	if len then
		coroutine.yield()
		inn = sock:receive(len)
	end

	-- uitvoer, log (in), http statuscode
	local uit, inL, status

	if inn then
		inL = string.format('%q', tostring(inn)):gsub('\n', '\\n')
	end

	-- VERTAAL!
	if pad == '/vt' then
		local internefout
		local ok,exp,fouten = xpcall(vt, debug.traceback, inn)
		if not ok then internefout = exp end

		if not ok then
			status = 500
			uit = "INTERNE FOUT!\n"..internefout
		else
			status = 200
			uit = naarweb(exp)
		end

	-- LEES!
	else
    pad = pad:gsub('%.%.', '%.')
    pad = pad:sub(2, #pad)
		if pad == '' then pad = 'index.html' end
		uit = file(pad)
		status = 200
		if not uit then
			uit = 'pagina niet gevonden'
			status = 404
		end
	end

	print(os.date(), status, pad, inL)

	-- header
	local h = string.format('HTTP/1.0 %d %s\r\n', status, statusberichten[status])
	local t = {}
	t[#t+1] = h
	t[#t+1] = "Host: localhost\r\n"
	t[#t+1] = "Server: Lua 5.2\r\n"
	t[#t+1] = "Content-Length: "..#uit.."\r\n"
	t[#t+1] = "\r\n"
	t[#t+1] = uit
	sendblocking(sock, table.concat(t))

	sock:close()
end

while true do
	local rs = socket.select(sockets)

	-- connect
	if rs[1] == server then
		local client = server:accept()
		sockets[client] = #sockets+1
		sockets[#sockets+1] = client
		coros[client] = coroutine.create(serveer, client)
		coroutine.resume(coros[client], client)
		table.remove(rs, 1)
	end

	-- data
	for i=#rs,1,-1 do
		local client = rs[i]
		local coro = coros[client]
		if not coro or coroutine.status(coro) ~= 'suspended' then
			table.remove(sockets, sockets[client]) --client)
			sockets[client] = nil
			coros[client] = nil
		else
			local unfinished,err = coroutine.resume(coros[client])
			if err then print('ERR', err) end
			if not unfinished then
				table.remove(sockets, sockets[client]) --client)
				sockets[client] = nil
				coros[client] = nil
			end
		end
	end

end
